language: python

python:
- "3.7-dev"
- "3.6"
- "3.5"
- "3.4"
- "3.3"
- "3.2"
- "2.7"
- "2.6"

env:
- LINT=false SCRIPT_SRC=local
- LINT=false SCRIPT_SRC=remote

before_script:
- source helpers.sh

install:
- if [ "$LINT" == "true" ]; then pip install flake8; fi

script:
# Test install
- cat_get_pip "$TRAVIS_PYTHON_VERSION" "$SCRIPT_SRC" | python -

# Static analysis
- if [ "$LINT" == "true" ]; then flake8 .; fi

matrix:
  fast_finish: true
  include:
  - python: 3.6
  env: LINT=true
