language: python

python:
- "3.7-dev"
- "3.6"
- "3.5"
- "3.4"
- "3.3"
- "3.2"
- "2.7"
- "2.6"

env:
- SCRIPT_SRC=local
- SCRIPT_SRC=remote

before_script:
- source .travis/helpers.sh

script:
- cat_get_pip "$TRAVIS_PYTHON_VERSION" "$SCRIPT_SRC" | python -

jobs:
  fast_finish: true
  include:
  - stage: Linters
    python: 3.6
    install:
    - pip install flake8
    script:
    - flake8 .
